export const siteConfig = {
  name: "Abul Hasnat Sakil",
  shortName: "sakil.dev",
  title: "Abul Hasnat Sakil | Full Stack AI & DevOps Engineer",
  description:
    "Engineering robust solutions at the intersection of Generative AI, Microservices, and Scalable Cloud Infrastructure.",
  email: "abulhasnatsakil.cu@gmail.com",
  location: "Kuala Lumpur, Malaysia / Remote Global",
  availability: "Available for new ventures & consulting",
  
  socials: {
    github: "https://github.com/hasnatsakil",
    linkedin: "https://www.linkedin.com/in/abul-hasnat-sakil-568618155/",
    fiverr: "https://www.fiverr.com/docxt112",
    email: "mailto:abulhasnatsakil.cu@gmail.com",
  },

  stats: {
    projectsShipped: "50+",
    studentsTaught: "1k+",
    uptimeGuaranteed: "99.9%",
  },

  projects: [
    {
      id: "visionary-ai-dash",
      title: "Visionary AI Dash",
      category: "AI/ML",
      year: "2024",
      problem: "Inefficient image processing causing severe latency bottlenecks in enterprise data pipelines.",
      solution: "Architected a distributed FastAPI backend orchestrated with Kubernetes and Azure AKS.",
      result: "40% Latency Reduction & 2x Throughput",
      tags: ["React", "FastAPI", "Azure", "Kubernetes", "PyTorch"],
      image: "/images/ai_dashboard.png",
      demoUrl: "https://github.com/hasnatsakil",
      githubUrl: "https://github.com/hasnatsakil",
      color: "primary",
    },
    {
      id: "auto-scale-framework",
      title: "Auto-Scale Cloud Framework",
      category: "DevOps/Cloud",
      year: "2024",
      problem: "Manual deployment bottlenecks causing unexpected server downtime during high traffic spikes.",
      solution: "Designed KEDA-based event-driven autoscaling with Terraform Infrastructure as Code and GitHub Actions.",
      result: "99.99% Guaranteed Zero-Downtime",
      tags: ["Docker", "Kubernetes", "Azure", "Terraform", "GitHub Actions"],
      image: "/images/cloud_infrastructure.png",
      demoUrl: "https://github.com/hasnatsakil",
      githubUrl: "https://github.com/hasnatsakil",
      color: "secondary",
    },
    {
      id: "secure-wallet-api",
      title: "High-Throughput Secure API",
      category: "Web/Full Stack",
      year: "2023",
      problem: "Data latency and rate-limiting issues on high-concurrency user requests.",
      solution: "Implemented OAuth2.0 authentication with Redis session caching and Node.js asynchronous workers.",
      result: "Sustaining 500k+ Daily API Requests",
      tags: ["Node.js", "Express", "Redis", "PostgreSQL", "Tailwind CSS"],
      image: "/images/secure_api.png",
      demoUrl: "https://github.com/hasnatsakil",
      githubUrl: "https://github.com/hasnatsakil",
      color: "tertiary",
    },
  ],

  services: [
    {
      id: "full-stack",
      module: "Module 01",
      title: "Full Stack Development",
      problem: "Bridging the gap between intuitive UI interfaces and high-performance server logic.",
      architecture: "Pixel-perfect React & Next.js frontends powered by robust Node.js and FastAPI backend microservices.",
      tags: ["React", "Next.js", "TypeScript", "Node.js"],
      outcome: "Production-ready, highly responsive web ecosystems.",
      color: "primary",
    },
    {
      id: "ai-ml",
      module: "Module 02",
      title: "AI & Machine Learning Solutions",
      problem: "Transforming static application workflows into data-driven, intelligent systems.",
      architecture: "Fine-tuning Large Language Models, PyTorch neural networks, and deploying high-throughput inference APIs.",
      tags: ["Python", "PyTorch", "FastAPI", "LLMs"],
      outcome: "Adaptive AI models seamlessly integrated into software.",
      color: "secondary",
    },
    {
      id: "devops",
      module: "Module 03",
      title: "DevOps & Cloud Architecture",
      problem: "Eliminating brittle deployment pipelines and manual environment failures.",
      architecture: "Containerized deployment workflows with Docker, Kubernetes orchestration, and Infrastructure as Code.",
      tags: ["Docker", "Kubernetes", "Terraform", "Azure"],
      outcome: "Automated CI/CD pipelines with zero-downtime reliability.",
      color: "tertiary",
    },
    {
      id: "saas",
      module: "Module 04",
      title: "SaaS & Systems Architecture",
      problem: "Building scalable multi-tenant infrastructure for ambitious startups.",
      architecture: "End-to-end multi-tenant database isolation, subscription integration, and secure user management.",
      tags: ["Next.js", "PostgreSQL", "Redis", "Stripe"],
      outcome: "Solid technical foundations ready to handle enterprise scale.",
      color: "primary-fixed",
    },
  ],
};
